import {
  Apple,
  Baby,
  Banana,
  Beef,
  Beer,
  BookOpen,
  BottleWine,
  Briefcase,
  BrushCleaning,
  CakeSlice,
  Camera,
  Candy,
  Car,
  Carrot,
  Cherry,
  CircleDot,
  Citrus,
  Clock,
  Coffee,
  Cookie,
  CookingPot,
  Croissant,
  Crown,
  Donut,
  Drumstick,
  Dumbbell,
  Egg,
  Fish,
  Flame,
  Flower2,
  Gamepad2,
  Gem,
  Gift,
  GlassWater,
  Grape,
  Hamburger,
  Headphones,
  Home,
  IceCreamCone,
  Laptop,
  Leaf,
  LeafyGreen,
  Luggage,
  Milk,
  Moon,
  Music,
  Nut,
  Package,
  Palette,
  PartyPopper,
  PawPrint,
  Percent,
  Pill,
  Pizza,
  Popcorn,
  Sandwich,
  Scissors,
  ShoppingBasket,
  Shirt,
  Shrimp,
  Smartphone,
  Snowflake,
  Sparkles,
  Sprout,
  Star,
  Stethoscope,
  Store,
  Sun,
  Tag,
  TreePine,
  Trees,
  Truck,
  UtensilsCrossed,
  Watch,
  Wheat,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export interface VendorCategoryIconOption {
  key: string;
  label: string;
  Icon: LucideIcon;
}

export const VENDOR_CATEGORY_ICON_OPTIONS: VendorCategoryIconOption[] = [
  { key: "basket", label: "Basket", Icon: ShoppingBasket },
  { key: "apple", label: "Apple", Icon: Apple },
  { key: "carrot", label: "Carrot", Icon: Carrot },
  { key: "fish", label: "Fish", Icon: Fish },
  { key: "milk", label: "Dairy", Icon: Milk },
  { key: "bread", label: "Bakery", Icon: CakeSlice },
  { key: "coffee", label: "Coffee", Icon: Coffee },
  { key: "pizza", label: "Pizza", Icon: Pizza },
  { key: "pill", label: "Pharmacy", Icon: Pill },
  { key: "shirt", label: "Fashion", Icon: Shirt },
  { key: "smartphone", label: "Electronics", Icon: Smartphone },
  { key: "flower", label: "Flowers", Icon: Flower2 },
  { key: "gift", label: "Gifts", Icon: Gift },
  { key: "sparkles", label: "Special", Icon: Sparkles },
  { key: "meat", label: "Meat", Icon: Beef },
  { key: "wine", label: "Drinks", Icon: BottleWine },
  { key: "ice-cream", label: "Ice cream", Icon: IceCreamCone },
  { key: "cookie", label: "Snacks", Icon: Cookie },
  { key: "egg", label: "Eggs", Icon: Egg },
  { key: "chili", label: "Spicy", Icon: Flame },
  { key: "leaf", label: "Organic", Icon: Leaf },
  { key: "cupcake", label: "Sweets", Icon: Cherry },
  { key: "bottle", label: "Beverages", Icon: GlassWater },
  { key: "grapes", label: "Fruits", Icon: Grape },
  { key: "soup", label: "Soups", Icon: CookingPot },
  { key: "salad", label: "Salads", Icon: LeafyGreen },
  { key: "croissant", label: "Pastries", Icon: Croissant },
  { key: "sandwich", label: "Sandwiches", Icon: Sandwich },
  { key: "burger", label: "Burgers", Icon: Hamburger },
  { key: "rice", label: "Grains", Icon: Wheat },
  { key: "noodles", label: "Hot meals", Icon: UtensilsCrossed },
  { key: "cheese", label: "Cheese", Icon: CircleDot },
  { key: "baby", label: "Baby", Icon: Baby },
  { key: "pet", label: "Pet", Icon: PawPrint },
  { key: "cleaning", label: "Cleaning", Icon: BrushCleaning },
  { key: "home", label: "Home", Icon: Home },
  { key: "hardware", label: "Hardware", Icon: Wrench },
  { key: "books", label: "Books", Icon: BookOpen },
  { key: "gaming", label: "Gaming", Icon: Gamepad2 },
  { key: "jewelry", label: "Jewelry", Icon: Gem },
  { key: "audio", label: "Audio", Icon: Headphones },
  { key: "computer", label: "Computers", Icon: Laptop },
  { key: "photo", label: "Photo", Icon: Camera },
  { key: "party", label: "Party", Icon: PartyPopper },
  { key: "seasonal", label: "Seasonal", Icon: TreePine },
  { key: "seafood", label: "Seafood", Icon: Shrimp },
  { key: "vegan", label: "Vegan", Icon: Sprout },
  { key: "frozen", label: "Frozen", Icon: Snowflake },
  { key: "popcorn", label: "Popcorn", Icon: Popcorn },
  { key: "beer", label: "Beer", Icon: Beer },
  { key: "donut", label: "Donuts", Icon: Donut },
  { key: "candy", label: "Candy", Icon: Candy },
  { key: "store", label: "General", Icon: Store },
  { key: "percent", label: "Deals", Icon: Percent },
  { key: "tea", label: "Tea", Icon: Coffee },
  { key: "breakfast", label: "Breakfast", Icon: Sun },
  { key: "lunch", label: "Lunch", Icon: Clock },
  { key: "dinner", label: "Dinner", Icon: Moon },
  { key: "dessert", label: "Dessert", Icon: CakeSlice },
  { key: "banana", label: "Banana", Icon: Banana },
  { key: "citrus", label: "Citrus", Icon: Citrus },
  { key: "poultry", label: "Poultry", Icon: Drumstick },
  { key: "nuts", label: "Nuts", Icon: Nut },
  { key: "health", label: "Health", Icon: Stethoscope },
  { key: "fitness", label: "Fitness", Icon: Dumbbell },
  { key: "beauty", label: "Beauty", Icon: Scissors },
  { key: "automotive", label: "Automotive", Icon: Car },
  { key: "delivery", label: "Delivery", Icon: Truck },
  { key: "music", label: "Music", Icon: Music },
  { key: "office", label: "Office", Icon: Briefcase },
  { key: "art", label: "Art", Icon: Palette },
  { key: "garden", label: "Garden", Icon: Trees },
  { key: "premium", label: "Premium", Icon: Crown },
  { key: "featured", label: "Featured", Icon: Star },
  { key: "hot-deals", label: "Hot deals", Icon: Tag },
  { key: "combo", label: "Combo", Icon: Package },
  { key: "watches", label: "Watches", Icon: Watch },
  { key: "luggage", label: "Luggage", Icon: Luggage },
];

const iconByKey = new Map(VENDOR_CATEGORY_ICON_OPTIONS.map((o) => [o.key, o]));

export function getVendorCategoryIcon(key: string | null | undefined) {
  if (!key) return iconByKey.get("basket") ?? VENDOR_CATEGORY_ICON_OPTIONS[0];
  return iconByKey.get(key) ?? VENDOR_CATEGORY_ICON_OPTIONS[0];
}

export function VendorCategoryIcon({
  iconKey,
  className,
}: {
  iconKey: string | null | undefined;
  className?: string;
}) {
  const { Icon } = getVendorCategoryIcon(iconKey);
  return <Icon className={className} aria-hidden />;
}
